##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#

DIRS=\
Metadata\
AliasAnalysis\
Utilities\
CAMP\
ObjTrace\
Qprofiler

#CAMP\
Metadata\
AliasAnalysis\
ICFG\
Utilities

#Metadata\
Utilities\
ICFG\
AliasAnalysis\
CAMP


include $(LEVEL)/Makefile.common
